import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Unplanned{process.env.MAPS_API_KEY}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Unplanned
        </h1>

        <p className={styles.description}>
          Random text
        </p>

        <div className={styles.grid}>
          <Link href="/about">
          <a className={styles.card}>
            <h2>About</h2>
            <p>Learn more about this fantastic unicorn app</p>
          </a>
          </Link>
          <Link href="/navigate">
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Navigate</h2>
            <p>Discover amazing places</p>
          </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}

export default Home
